# Generated by Django 6.0.2 on 2026-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syntaxalign", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="product",
            name="delivery_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="file",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("fullstack", "Full-Stack"),
                    ("design", "Graphics/Design"),
                ],
                max_length=20,
            ),
        ),
    ]
