# Generated by Django 6.0.2 on 2026-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "syntaxalign",
            "0002_remove_order_delivered_remove_product_delivery_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[("business", "Business"), ("personal", "Personal")],
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employee_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "backup_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "backup_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("project_scope", models.TextField(blank=True, null=True)),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timeline", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("personal_project_details", models.TextField(blank=True, null=True)),
                (
                    "estimated_budget",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_timeline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
