# Generated by Django 6.0.2 on 2026-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syntaxalign", "0003_developmentinquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[("business", "Business"), ("personal", "Personal")],
                        max_length=20,
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo Design"),
                            ("branding", "Brand Identity"),
                            ("social", "Social Media Design"),
                            ("uiux", "UI/UX Design"),
                            ("marketing", "Marketing Materials"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "proposed_offer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "expected_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
