# Generated by Django 6.0.2 on 2026-02-12 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syntaxalign", "0004_designinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designinquiry",
            name="expected_duration",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="designinquiry",
            name="full_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters and spaces (2-50 characters)",
                        regex="^[a-zA-Z\\s]{2,50}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="designinquiry",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain 7-15 digits and may include +, spaces or -",
                        regex="^\\+?[\\d\\s\\-]{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="designinquiry",
            name="proposed_offer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="backup_phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain 7-15 digits and may include +, spaces or -",
                        regex="^\\+?[\\d\\s\\-]{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="company_phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain 7-15 digits and may include +, spaces or -",
                        regex="^\\+?[\\d\\s\\-]{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="employee_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters and spaces (2-50 characters)",
                        regex="^[a-zA-Z\\s]{2,50}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="employee_phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain 7-15 digits and may include +, spaces or -",
                        regex="^\\+?[\\d\\s\\-]{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters and spaces (2-50 characters)",
                        regex="^[a-zA-Z\\s]{2,50}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developmentinquiry",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain 7-15 digits and may include +, spaces or -",
                        regex="^\\+?[\\d\\s\\-]{7,15}$",
                    )
                ],
            ),
        ),
    ]
