# Generated by Django 6.0.2 on 2026-02-12 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syntaxalign", "0005_alter_designinquiry_expected_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("fullstack", "Full-Stack"),
                            ("design", "Graphics/Design"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("graphic", "Graphic Design"),
                    ("development", "Web Development"),
                ],
                default=6.0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="demo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="syntaxalign.legacyproduct",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "whatsapp",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must contain 7-15 digits and may include +, spaces or -",
                                regex="^\\+?[\\d\\s\\-]{7,15}$",
                            )
                        ],
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syntaxalign.product",
                    ),
                ),
            ],
        ),
    ]
